-- *************************************************************
-- Assignment1Part3H
-- practice Date_Format function
-- created for IT2351 by Elijah King, Spring 2021
-- *************************************************************
